#!/usr/bin/env python

import os


def main():
    try:
        from ztf_dr_downloader.main import cmd

    except ImportError as exc:
        raise ImportError from exc

    cmd()


if __name__ == '__main__':
    main()
