#!/usr/bin/env python

import os


def main():
    try:
        FILE_PATH = os.path.dirname(os.path.abspath(__file__))
        PROJECT_PATH = os.path.abspath(os.path.join(FILE_PATH, ".."))
        from src.main import cmd

    except ImportError as exc:
        raise ImportError from exc

    cmd()


if __name__ == '__main__':
    main()
